tcpreplay: fix path to tcpdump
Without this change, running tcpreplay with -v results in:

    Fatal Error: Unable to exec tcpdump: Permission denied

The reason is that tcpreplay tries to execute exactly the path passed
via the --with-tcpdump configure switch.