mpvScripts.buildLua: fix buildLua's runtime-dependencies argument
Fix buildLua's runtime-dependencies argument to prevent the following
nasty error, introduced in commit e67cceafda6d ("mpvScripts.twitch-chat:
refactor using buildLua's `runtime-dependencies`"):

    error: expected a list but found a set: { [...] }

Fixes: e2596ac22d42 ("mpvScripts.buildLua: add a `runtime-dependencies` option")